/* /////////////////////////////////////////////////////////////////////////
cpGUID.h
cpGUID Declaration and C Utilities
///////////////////////////////////////////////////////////////////////// */
#ifndef CPGUID_H_46DAC5037E704826B04DEB53A1899212
#define CPGUID_H_46DAC5037E704826B04DEB53A1899212


#include "srvis/general/cpresult.h"
#include "srvis/general/ExportSrvISApi.h"


/**@name C cpGUID Utilities  */
/*@{*/


#if !defined (CPGUID_DEFINED)
#define CPGUID_DEFINED

struct tag_cpGUID 
{
	unsigned int   Data1;
	unsigned short Data2;
	unsigned short Data3;
	unsigned char  Data4[8];
};


/** 128 bit of unique id. Match COM's GUID definition. */
typedef struct tag_cpGUID cpGUID;

#endif /* CPGUID_DEFINED */



/** min length required for the representation of cpGUID as string. */
enum { CPGUID_STR_LEN = 39 };



/** 
Create new cpGUID, and put in *pguid.  
@param  pguid [out] address of cpGUID to fill
@return success/fail  */
CPSRV_EXPORT_C_API 
cpresult cpCreateGuid (cpGUID * pguid);



/** 
Converts a cpGUID into a string of printable characters. 
The allocated string format is {xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx}. 
@param  pguid [IN]  cpGUID to be converted.
@param  psz   [OUT] Address of char* pointer variable that receives a 
                    pointer to the resulting string. The caller is 
                    responsible for freeing the memory allocated for 
                    the string by calling srvFreeString.
@return CP_E_OUTOFMEMORY or CP_S_OK  */
CPSRV_EXPORT_C_API 
cpresult cpStringFromGUID (const cpGUID * pguid, char ** psz);



/** 
Converts a cpGUID into a string of printable characters.  
@param  pguid  [IN]  ptr to cpGUID to be converted
@param  sz     [OUT] Pointer to a caller-allocated string variable to contain 
                     the resulting string on return.
@param  cchMax [IN]  Number of characters available in the buffer indicated 
                     by sz. The min size of sz should be CPGUID_STR_LEN
@return 0 (zero): Array at sz is too small to contain a string 
                  representation of a cpGUID. 
        Non-zero value: The number of characters in the returned string, 
                        including the null terminator  */
CPSRV_EXPORT_C_API 
unsigned int cpStringFromGUID2 (const cpGUID * pguid, char * sz, unsigned int cchMax);



/** 
Converts a string generated by the cpStringFromGUID function back into the 
original cpGUID. 
@param  sz    [IN]  Pointer to the string representation of the cpGUID
@param  pguid [OUT] Pointer to the requested cpGUID on return
@return CP_E_INVALIDARG and CP_S_OK  */
CPSRV_EXPORT_C_API 
cpresult cpGUIDFromString (const char* sz, cpGUID * pguid);




/*@}*/

#endif /* CPGUID_H_46DAC5037E704826B04DEB53A1899212 */
/* //////////////////////////// EOF cpGUID.h //////////////////////////// */



